name: Run Tool Pytest

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: ./api/requirements.txt

      - name: Install dependencies
        run: pip install -r ./api/requirements.txt

      - name: cd api
        run: cd api

      - name: Run pytest
        run: pytest ./tests/integration_tests/tools/
